test:
    node DeviceMappings.test.js
    node DeviceMapper.test.js
    node Animations.test.js
    node ClipGestures.test.js
    node ClipLauncher.test.js
    node Twister.test.js
    node Launchpad.test.js
    node LaunchpadLane.test.js
    node LaunchpadQuadrant.test.js
    node LaunchpadModeSwitcher.test.js
    node LaunchpadTopButtons.test.js
    node NanoKey2.test.js
    node Page_ClipLauncher.test.js
    node Page_ColorPalette.test.js
    node Page_DebugActions.test.js
    node Page_MainControl.test.js
    node Page_MarkerManager.test.js
    node DeviceQuadrant.test.js
    node DeviceSelector.test.js
    node MapperCache.test.js
    node Controller.test.js
    node RolandPiano.test.js
    node Pager.test.js
    node Pages.test.js
    node ProjectExplorer.test.js
    node BitwigActions.test.js
    node Bitwig.test.js
    node TD17Remapper.test.js
    node FrequalizerDevice.test.js
    node TwisterPainter.test.js
    node FrequalizerTwisterMapper.test.js
    node FrequalizerPadMapper.test.js
    node DrumPadMapper.test.js
    node QuickActions.test.js
    node FavBar.test.js
    node live/Pager.test.js
    node live/Launchpad.test.js
    node live/Twister.test.js
    node live/Bitwig.test.js
    node live/MarkerSets.test.js
    node live/Page_Control.test.js
    node live/Page_ProjectExplorer.test.js
    node live/MainPager.test.js
    node live/SongPager.test.js
    node live/BarPager.test.js
    node live/ModeSwitcher.test.js
    node live/SideButtons.test.js
    node live/Controller.test.js
