# Local type stubs for the parts of `mido` (1.3.x) this project uses.
# mido ships no py.typed marker and has no published stub package, so these
# are hand-written from the source in site-packages. Extend as usage grows.

from collections.abc import Iterator
from typing import Any

class Message:
    # `type` is read-only at runtime; the rest are set dynamically from the
    # message spec, so not every attribute exists on every message type.
    type: str
    channel: int
    note: int
    velocity: int
    control: int
    value: int
    time: float
    data: tuple[int, ...]

    def __init__(self, type: str, skip_checks: bool = ..., **args: Any) -> None: ...
    def copy(self, skip_checks: bool = ..., **overrides: Any) -> Message: ...
    def bytes(self) -> list[int]: ...
    def bin(self) -> bytearray: ...
    def hex(self, sep: str = ...) -> str: ...

class BaseInput:
    name: str | None
    closed: bool
    def iter_pending(self) -> Iterator[Message]: ...
    def poll(self) -> Message | None: ...
    def receive(self, block: bool = ...) -> Message: ...
    def close(self) -> None: ...
    def __iter__(self) -> Iterator[Message]: ...
    def __enter__(self) -> BaseInput: ...
    def __exit__(self, *args: object) -> None: ...

class BaseOutput:
    name: str | None
    closed: bool
    def send(self, msg: Message) -> None: ...
    def reset(self) -> None: ...
    def panic(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> BaseOutput: ...
    def __exit__(self, *args: object) -> None: ...

# Injected onto the module by set_backend() at import time.
def open_input(
    name: str | None = ..., virtual: bool = ..., callback: Any = ..., **kwargs: Any
) -> BaseInput: ...
def open_output(
    name: str | None = ..., virtual: bool = ..., autoreset: bool = ..., **kwargs: Any
) -> BaseOutput: ...
